Algoritmo "comissão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  Cintia Pinho
// Descrição   : Calcular comissão
// Autor(a)    : Gabriela Ripoli
// Data atual  : 24/06/2021
Var
quant, preco único = real

Inicio
//entrada
escreval("Digite o preço único:")
leia(preço único)
escreval("Digite a quantidade")
leia(quant)

//execução

comissão<- venda total-5%

//saída

escreval("A comissãodo vendendo é de",comissão")

Fimalgoritmo