Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cíntia Pinho
// Descrição   : Soma dos quadrados
// Autor(a)    : Gabriela Ripoli
// Data atual  : 24/06/2021
Var
lads,resultado= real


Inicio
// entrada
escreval("Digite os 4 lados")
leia(lados)

// execução
resultado<- (a^2)+(b^2)+(c^2)+(d^2)

// saída
escreval(resultado ",resultado")


Fimalgoritmo
