Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cíntia Pinho
// Descrição   : Soma dos quadrados
// Autor(a)    : Gabriela Ripoli
// Data atual  : 24/06/2021
Var
quadrado,resultado= real


Inicio
// entrada
escreval("Digite 4 numeros")
leia(quadrado)

// execução
resultado<- (a^2)+(b^2)+(c^2)+(d^2)

// saída
escreval(resultado ",resultado")


Fimalgoritmo